### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by nightfuryyy** [louisdo/IDEX#1]
Chào bác. Em thử code thì thấy detect cái đúng cái sai. Nhưng đến phần detect với grap thì sai hoàn toàn.

**Comment by louisdo** [comment]
Grap là gi thế bác ơi

**Comment by louisdo** [comment]
bác có thể cho em biết là sai cái gì không ạ? Em vẫn đang update project này

**Comment by nightfuryyy** [comment]
Em cho 1 ảnh chứng  minh thư chuẩn, thẳng đứng vào. Kết quả nó vẫn ko nhận được. 
Với cả đoạn code này
"# import matplotlib
# matplotlib.use('tkagg')"
bị lỗi nên em comment nó luôn :v

**Comment by louisdo** [comment]
Em cũng đoán được vấn đề rồi bác, bác thử chụp một ảnh k bị sấp bóng đi, trong phần limitations em có ghi là chương trình vẫn chưa hoạt động được với những ảnh sấp bóng, Em hỏi thêm là chương trình k cho ra kết quả hay cho ra kết quả nhưng sai hả bác?
coòn cái matplotlib kia thì bác pip install chưa?

**Comment by nightfuryyy** [comment]
![overview](https://user-images.githubusercontent.com/34280017/63208628-bd346880-c100-11e9-8c1b-b7aa9450c418.png)

Tất nhiên là em install rồi @@ tra gg cũng thấy nhiều người bị, nhưng nó ko ảnh hưởng nên kệ. Như em nói ở trên đó, bước detect card để co về hình chữ nhật, cái được cái ko. Bước ocr ko ra j cái j hết.

**Comment by louisdo** [comment]
đấy là hạn chế của chương trình của em đấy bác, bác cứ chụp một tấm có lighting tốt là nó sẽ chạy được, em tính sẽ có giải pháp giải quyết cái này khi mà em có thời gian. Em xin phép close cái này nha bác.

**Comment by louisdo** [comment]
đấy là hạn chế của chương trình của em đấy bác, bác cứ chụp một tấm có lighting tốt là nó sẽ chạy được, em tính sẽ có giải pháp giải quyết cái này khi mà em có thời gian.

**Comment by louisdo** [comment]
bác cho 1 fork ủng hộ em nhé

**Comment by nightfuryyy** [comment]
vl xoá cmt luôn ! thua !

**Comment by louisdo** [comment]
Em xóa cmt của e mà bác, vì e lỡ ấn comment and close, chả hiểu sao nó lại xóa cả cmt của bác.

Nightfuryyy deleted comment:
overview
Tất nhiên là em install rồi @@ tra gg cũng thấy nhiều người bị, nhưng nó ko ảnh hưởng nên kệ. Như em nói ở trên đó, bước detect card để co về hình chữ nhật, cái được cái ko. Bước ocr ko ra j  cái j hết
