### ISSUE TITLE
Lỗi import

### ISSUE THREAD

**Issue by nttungub** [louisdo/IDEX#2]
Mình chạy python run.py gặp lỗi này:
from object_detection.utils import spatial_transform_ops as spatial_ops
ImportError: cannot import name 'spatial_transform_ops'

Giờ xử lý thế nào bạn? Cảm ơn bạn.

**Comment by louisdo** [comment]
xin lỗi bạn mình rep hơi muộn, bạn có thể chụp toàn bộ đoạn lỗi không?

**Comment by louisdo** [comment]
à mình biết rồi, bạn clone code từ link ở dưới về rồi set environment variable cho models/research/object_detection nhé ^^

https://github.com/tensorflow/models

**Comment by nttungub** [comment]
Cảm ơn bạn.  Mình hết lỗi này rồi.
Tuy nhiên mình thử với một ảnh cccd thì đều báo mode RGB, H, S, HS failed hết.

**Comment by louisdo** [comment]
mình có nhắc đến hạn chế này ở phần mô tả rồi ^^, để chương trình hoạt động tốt nhất thì ảnh chỉ có 1 cccd, background k quá nhiễu và k quá đồng màu với cccd và k bị sấp bóng nữa. Lý do vì sao lại hạn chế như vậy là vì mình dùng classical computer vision để scan cccd.

**Comment by louisdo** [comment]
nếu project có giúp bạn đk phần nào thì star với fork nhé :))))

**Comment by nttungub** [comment]
OK. Cảm ơn bạn. Mình cũng mới tìm hiều về chủ đề này.
Nếu có thể bạn chia sẻ giúp mình một ảnh mà bạn test cho ra kết quả tốt vào email: johndoe201608@gmail.com nhé.
