### ISSUE TITLE
Hình demo

### ISSUE THREAD

**Issue by anhhna** [louisdo/IDEX#3]
Bạn ơi cho mình hỏi bạn có hình để demo không, vì mình test thử một số hình CMND thì không chính xác lắm, bạn có thể gửi cho mình một tấm hình demo ra kết quả chính xác để mình dựa vào hình đó mình biết được để có kết quả chính xác thì cần hình như thế nào, cám ơn bạn!

**Comment by louisdo** [comment]
bạn cho mình email để mình gửi qua nhé

**Comment by anhhna** [comment]
vâng cám ơn bạn, email của mình là: anhhna@gmail.com
